## Analyze whether SNWD varies more from year to year or from place to place.

In [2]:
import pandas as pd
import numpy as np
import urllib
import math

In [3]:
import findspark
findspark.init()

from pyspark import SparkContext
#sc.stop()
sc = SparkContext(master="local[3]",pyFiles=['lib/numpy_pack.py','lib/spark_PCA.py','lib/computeStats.py'])

from pyspark import SparkContext
from pyspark.sql import *
sqlContext = SQLContext(sc)

In [4]:
import sys
sys.path.append('./lib')

import numpy as np
from numpy_pack import packArray,unpackArray
from spark_PCA import computeCov
from computeStats import computeOverAllDist, STAT_Descriptions

In [6]:
### Read the data frame from pickle file

data_dir='../../Data/Weather'
file_index='BSBSSSSS'
meas='TOBS'

from pickle import load

#read statistics
filename=data_dir+'/STAT_%s.pickle'%file_index
STAT,STAT_Descriptions = load(open(filename,'rb'))
print('keys from STAT=',STAT.keys())

#!ls -ld $data_dir/*.parquet

#read data
filename=data_dir+'/decon_%s_%s.parquet'%(file_index,meas)

df=sqlContext.read.parquet(filename)
print(df.count())
df.show(2)

('keys from STAT=', ['TMIN', 'TOBS', 'TMAX', 'SNOW', 'SNWD', 'PRCP'])
1473
+------------------+-----------------+------------------+---------+--------+--------+---------+-----------+------------------+------------------+------------------+--------------------+-----------+-----------+------+--------------------+------+
|           coeff_1|          coeff_2|           coeff_3|elevation|   label|latitude|longitude|measurement|             res_1|             res_2|             res_3|            res_mean|    station|  total_var|undefs|              vector|  year|
+------------------+-----------------+------------------+---------+--------+--------+---------+-----------+------------------+------------------+------------------+--------------------+-----------+-----------+------+--------------------+------+
| 717.5459612227579|96.80398671865137|-61.50489335794748|     56.4|BSBSSSSS| 30.7836| -83.5692|       TOBS|0.5299298728719344|0.5218511737391858|0.5159160510912769|0.061538323241307834|USC00097276|2.0402826E7|     5|[90 59 E0 58 98 5...|1943.0|
|-845.6739032997987|67.24721417081365| 76.99052771547218|     64.0|BSBSSSSS|  31.615| -85.0494|       TOBS|0.5220123405378542|0.5192139025324356|0.5160616764669335| 0.14549444667277778|USC00093578|1.0026299E7|     1|[30 55 00 46 E0 D...|2008.0|
+------------------+-----------------+------------------+---------+--------+--------+---------+-----------+------------------+------------------+------------------+--------------------+-----------+-----------+------+--------------------+------+
only showing top 2 rows

In [7]:
print df.columns

['coeff_1', 'coeff_2', 'coeff_3', 'elevation', 'label', 'latitude', 'longitude', 'measurement', 'res_1', 'res_2', 'res_3', 'res_mean', 'station', 'total_var', 'undefs', 'vector', 'year']

In [8]:
#extract longitude and latitude for each station
feature='coeff_1'
sqlContext.registerDataFrameAsTable(df,'weather')
#Features=', '.join(['coeff_1', 'coeff_2', 'coeff_3', 'elevation', 'latitude', 'longitude',\
#          'res_1', 'res_2', 'res_3', 'res_mean', 'year'])
Features='station, year, coeff_2'
Query="SELECT %s FROM weather"%Features
print(Query)
pdf = sqlContext.sql(Query).toPandas()
pdf.head()

SELECT station, year, coeff_2 FROM weather

       station    year     coeff_2
0  USC00097276  1943.0   96.803987
1  USC00093578  2008.0   67.247214
2  USC00013761  1961.0 -230.185236
3  USC00096087  1936.0 -117.326636
4  USC00096087  1986.0 -113.419203

In [9]:
year_station_table=pdf.pivot(index='year', columns='station', values='coeff_2')
year_station_table.head(10)

station,USC00013761,USC00014895,USC00080025,USC00080804,USC00081020,USC00081022,USC00081356,USC00081544,USC00081601,USC00081775,...,USC00095585,USC00096038,USC00096087,USC00096356,USC00097165,USC00097276,USC00098666,USC00098703,USC00099519,USW00012832
year,,,,,,,,,,,,,,,,,,,,,
1901.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,387.674622,267.127838,NaN,NaN,112.252043,NaN,NaN,NaN,NaN,NaN
1902.0,NaN,NaN,NaN,NaN,NaN,NaN,-123.280917,NaN,NaN,NaN,...,-4.766199,NaN,NaN,NaN,-129.520096,NaN,NaN,NaN,NaN,NaN
1903.0,NaN,NaN,NaN,NaN,NaN,NaN,112.901721,NaN,NaN,NaN,...,217.389943,NaN,NaN,NaN,235.433208,NaN,NaN,NaN,NaN,NaN
1904.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.062865,NaN,NaN,NaN,-62.845152,NaN,NaN,NaN,NaN,NaN
1905.0,NaN,-205.171665,NaN,NaN,NaN,NaN,-178.206204,NaN,NaN,NaN,...,-68.367749,NaN,NaN,NaN,-207.910014,NaN,NaN,NaN,NaN,NaN
1906.0,NaN,248.712018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-66.138455,NaN,NaN,NaN,NaN,NaN
1907.0,NaN,299.362774,NaN,NaN,NaN,NaN,-458.957161,NaN,NaN,NaN,...,237.249940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1908.0,NaN,-189.625735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-35.960116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1909.0,NaN,179.634730,NaN,-511.124308,NaN,NaN,NaN,NaN,NaN,NaN,...,152.048390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1910.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Estimating the effect of the year vs the effect of the station

To estimate the effect of time vs. location on the first eigenvector coefficient we
compute:

* The average row: `mean-by-station`
* The average column: `mean-by-year`

We then compute the RMS before and after subtracting either  the row or the column vector.

In [10]:
def RMS(Mat):
    return np.sqrt(np.nanmean(Mat**2))

mean_by_year=np.nanmean(year_station_table,axis=1)
mean_by_station=np.nanmean(year_station_table,axis=0)
tbl_minus_year = (year_station_table.transpose()-mean_by_year).transpose()
tbl_minus_station = year_station_table-mean_by_station

print 'total RMS                   = ',RMS(year_station_table)
print 'RMS removing mean-by-station= ',RMS(tbl_minus_station)
print 'RMS removing mean-by-year   = ',RMS(tbl_minus_year)

total RMS                   =  198.26720752
RMS removing mean-by-station=  190.278337595
RMS removing mean-by-year   =  106.61472991

In [11]:
T=year_station_table
print 'initial RMS=',RMS(T)
for i in range(5):
    mean_by_year=np.nanmean(T,axis=1)
    T=(T.transpose()-mean_by_year).transpose()
    print i,'after removing mean by year    =',RMS(T)
    mean_by_station=np.nanmean(T,axis=0)
    T=T-mean_by_station
    print i,'after removing mean by stations=',RMS(T)

initial RMS= 198.26720752
0 after removing mean by year    = 106.61472991
0 after removing mean by stations= 99.2194945651
1 after removing mean by year    = 98.8803138959
1 after removing mean by stations= 98.8040249417
2 after removing mean by year    = 98.7725685091
2 after removing mean by stations= 98.7575048341
3 after removing mean by year    = 98.7499754693
3 after removing mean by stations= 98.7461457463
4 after removing mean by year    = 98.7441791481
4 after removing mean by stations= 98.7431630379