## Analyze whether SNWD varies more from year to year or from place to place.

In [1]:
import pandas as pd
import numpy as np
import urllib
import math

In [2]:
import findspark
findspark.init()

from pyspark import SparkContext
#sc.stop()
sc = SparkContext(master="local[3]",pyFiles=['lib/numpy_pack.py','lib/spark_PCA.py','lib/computeStats.py'])

from pyspark import SparkContext
from pyspark.sql import *
sqlContext = SQLContext(sc)

In [3]:
import sys
sys.path.append('./lib')

import numpy as np
from numpy_pack import packArray,unpackArray
from spark_PCA import computeCov
from computeStats import computeOverAllDist, STAT_Descriptions

In [4]:
### Read the data frame from pickle file

data_dir='../../Data/Weather'
#file_index='BBBSBBBB'
file_index='SSSSBSBB'
meas='SNWD'

from pickle import load

#read statistics
filename=data_dir+'/STAT_%s.pickle'%file_index
STAT,STAT_Descriptions = load(open(filename,'rb'))
print('keys from STAT=',STAT.keys())

#!ls -ld $data_dir/*.parquet

#read data
filename=data_dir+'/decon_%s_%s.parquet'%(file_index,meas)

df=sqlContext.read.parquet(filename)
print(df.count())
df.show(2)

('keys from STAT=', ['TMIN', 'TOBS', 'TMAX', 'SNOW', 'SNWD', 'PRCP'])
362
+------------------+-------------------+-----------------+---------+--------+--------+---------+-----------+------------------+------------------+------------------+------------------+-----------+---------+------+--------------------+------+
|           coeff_1|            coeff_2|          coeff_3|elevation|   label|latitude|longitude|measurement|             res_1|             res_2|             res_3|          res_mean|    station|total_var|undefs|              vector|  year|
+------------------+-------------------+-----------------+---------+--------+--------+---------+-----------+------------------+------------------+------------------+------------------+-----------+---------+------+--------------------+------+
| 33.14001142374873| -26.04826506027524|27.47328642709544|   1935.5|SSSSBSBB|    33.0|-108.0833|       SNWD|0.9805858927840809|0.9733242488229749|0.9593946296815167|0.9466380752145716|USC00293615|  64517.0|    23|[00 00 00 00 00 0...|1915.0|
|46.284535619641986|-24.333368415327293|75.41312470598655|   1478.3|SSSSBSBB| 33.2367|-107.2681|       SNWD|0.9495788220280149| 0.935642581627634|0.8017874460970116|0.8955435090602019|USW00093045|  47443.0|     0|[00 00 00 00 00 0...|1956.0|
+------------------+-------------------+-----------------+---------+--------+--------+---------+-----------+------------------+------------------+------------------+------------------+-----------+---------+------+--------------------+------+
only showing top 2 rows

In [5]:
print df.columns

['coeff_1', 'coeff_2', 'coeff_3', 'elevation', 'label', 'latitude', 'longitude', 'measurement', 'res_1', 'res_2', 'res_3', 'res_mean', 'station', 'total_var', 'undefs', 'vector', 'year']

In [6]:
#extract longitude and latitude for each station
feature='coeff_1'
sqlContext.registerDataFrameAsTable(df,'weather')
#Features=', '.join(['coeff_1', 'coeff_2', 'coeff_3', 'elevation', 'latitude', 'longitude',\
#          'res_1', 'res_2', 'res_3', 'res_mean', 'year'])
Features='station, year, coeff_1, coeff_2, coeff_3'
Query="SELECT %s FROM weather"%Features
print(Query)
pdf = sqlContext.sql(Query).toPandas()
pdf.head()

SELECT station, year, coeff_1, coeff_2, coeff_3 FROM weather

       station    year    coeff_1     coeff_2     coeff_3
0  USC00293615  1915.0  33.140011  -26.048265   27.473286
1  USW00093045  1956.0  46.284536  -24.333368   75.413125
2  USW00093045  1960.0  11.012031  205.269408  119.597835
3  USW00093045  1966.0   6.014860    7.982526  -82.929480
4  USW00093045  1967.0 -17.840702   85.627521   76.644242

In [7]:
year_station_table=pdf.pivot(index='year', columns='station', values='coeff_2')
year_station_table.head(10)

station,US1NMDA0112,US1NMOT0039,US1NMOT0056,USC00022754,USC00290199,USC00290268,USC00291252,USC00291286,USC00291790,USC00291910,...,USC00299686,USC00299691,USC00299697,USC00299720,USC00299806,USW00023002,USW00023039,USW00023046,USW00093045,USW00093063
year,,,,,,,,,,,,,,,,,,,,,
1901.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1905.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1909.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1913.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1915.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-23.565846,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1916.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,52.697306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1917.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1918.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1923.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Estimating the effect of the year vs the effect of the station

To estimate the effect of time vs. location on the first eigenvector coefficient we
compute:

* The average row: `mean-by-station`
* The average column: `mean-by-year`

We then compute the RMS before and after subtracting either  the row or the column vector.

In [8]:
def RMS(Mat):
    return np.sqrt(np.nanmean(Mat**2))

year_station_table=pdf.pivot(index='year', columns='station', values='coeff_1')
mean_by_year=np.nanmean(year_station_table,axis=1)
mean_by_station=np.nanmean(year_station_table,axis=0)
tbl_minus_year = (year_station_table.transpose()-mean_by_year).transpose()
tbl_minus_station = year_station_table-mean_by_station

print 'coeff_1'
print 'total RMS                   = ',RMS(year_station_table)
print 'RMS removing mean-by-station= ',RMS(tbl_minus_station)
print 'fraction explained  =', (RMS(year_station_table) - RMS(tbl_minus_station)) / RMS(year_station_table) 
print 'RMS removing mean-by-year   = ',RMS(tbl_minus_year)
print 'fraction explained  =', (RMS(year_station_table) - RMS(tbl_minus_year)) / RMS(year_station_table)

coeff_1
total RMS                   =  557.468013648
RMS removing mean-by-station=  396.027732492
fraction explained  = 0.289595595091
RMS removing mean-by-year   =  455.207244626
fraction explained  = 0.183437913061

In [9]:
def RMS(Mat):
    return np.sqrt(np.nanmean(Mat**2))

year_station_table=pdf.pivot(index='year', columns='station', values='coeff_2')
mean_by_year=np.nanmean(year_station_table,axis=1)
mean_by_station=np.nanmean(year_station_table,axis=0)
tbl_minus_year = (year_station_table.transpose()-mean_by_year).transpose()
tbl_minus_station = year_station_table-mean_by_station

print 'coeff_2'
print 'total RMS                   = ',RMS(year_station_table)
print 'RMS removing mean-by-station= ',RMS(tbl_minus_station)
print 'fraction explained', (RMS(year_station_table) - RMS(tbl_minus_station)) / RMS(year_station_table) 
print 'RMS removing mean-by-year   = ',RMS(tbl_minus_year)
print 'fraction explained', (RMS(year_station_table) - RMS(tbl_minus_year)) / RMS(year_station_table)

coeff_2
total RMS                   =  219.387409639
RMS removing mean-by-station=  180.900661223
fraction explained 0.175428245766
RMS removing mean-by-year   =  177.524794609
fraction explained 0.190815941074

In [10]:
def RMS(Mat):
    return np.sqrt(np.nanmean(Mat**2))

year_station_table=pdf.pivot(index='year', columns='station', values='coeff_3')
mean_by_year=np.nanmean(year_station_table,axis=1)
mean_by_station=np.nanmean(year_station_table,axis=0)
tbl_minus_year = (year_station_table.transpose()-mean_by_year).transpose()
tbl_minus_station = year_station_table-mean_by_station

print 'coeff_3'
print 'total RMS                   = ',RMS(year_station_table)
print 'RMS removing mean-by-station= ',RMS(tbl_minus_station)
print 'fraction explained', (RMS(year_station_table) - RMS(tbl_minus_station)) / RMS(year_station_table) 
print 'RMS removing mean-by-year   = ',RMS(tbl_minus_year)
print 'fraction explained', (RMS(year_station_table) - RMS(tbl_minus_year)) / RMS(year_station_table)

coeff_3
total RMS                   =  167.950634625
RMS removing mean-by-station=  165.161377532
fraction explained 0.0166076007916
RMS removing mean-by-year   =  136.586038427
fraction explained 0.186748899566

In [11]:
T=year_station_table
print 'initial RMS=',RMS(T)
for i in range(5):
    mean_by_year=np.nanmean(T,axis=1)
    T=(T.transpose()-mean_by_year).transpose()
    print i,'after removing mean by year    =',RMS(T)
    mean_by_station=np.nanmean(T,axis=0)
    T=T-mean_by_station
    print i,'after removing mean by stations=',RMS(T)

initial RMS= 167.950634625
0 after removing mean by year    = 136.586038427
0 after removing mean by stations= 132.796386253
1 after removing mean by year    = 132.106135683
1 after removing mean by stations= 131.896684003
2 after removing mean by year    = 131.809490304
2 after removing mean by stations= 131.763833849
3 after removing mean by year    = 131.736541191
3 after removing mean by stations= 131.719111817
4 after removing mean by year    = 131.707616332
4 after removing mean by stations= 131.699905909