## Analyze whether TOBS varies more from year to year or from place to place.

In [1]:
import pandas as pd
import numpy as np
import urllib
import math

In [2]:
import findspark
findspark.init()

from pyspark import SparkContext
# sc.stop()
sc = SparkContext(master="local[3]",pyFiles=['lib/numpy_pack.py','lib/spark_PCA.py','lib/computeStats.py'])

from pyspark import SparkContext
from pyspark.sql import *
sqlContext = SQLContext(sc)

In [3]:
import sys
sys.path.append('./lib')

import numpy as np
from numpy_pack import packArray,unpackArray
from spark_PCA import computeCov
from computeStats import computeOverAllDist, STAT_Descriptions

In [4]:
### Read the data frame from pickle file

data_dir='../../Data/Weather'
file_index='BSBSSSSB'
meas='TOBS'

from pickle import load

#read statistics
filename=data_dir+'/STAT_%s.pickle'%file_index
STAT,STAT_Descriptions = load(open(filename,'rb'))
print('keys from STAT=',STAT.keys())

#!ls -ld $data_dir/*.parquet

#read data
filename=data_dir+'/decon_%s_%s.parquet'%(file_index,meas)

df=sqlContext.read.parquet(filename)
print(df.count())
df.show(2)

('keys from STAT=', ['TMIN', 'TOBS', 'TMAX', 'SNOW', 'SNWD', 'PRCP'])
1267
+------------------+-------------------+-------------------+------------------+---------+--------+--------+---------+-----------+------------------+-------------------+------------------+-------------------+-------------------+-----------+----------+------+--------------------+------+
|           coeff_1|            coeff_2|            coeff_3|           coeff_4|elevation|   label|latitude|longitude|measurement|             res_1|              res_2|             res_3|              res_4|           res_mean|    station| total_var|undefs|              vector|  year|
+------------------+-------------------+-------------------+------------------+---------+--------+--------+---------+-----------+------------------+-------------------+------------------+-------------------+-------------------+-----------+----------+------+--------------------+------+
|1011.6915841045098| 148.11958105424887|  36.57111369826823|-56.23017691454619|    175.3|BSBSSSSB| 32.8694| -85.1892|       TOBS|0.4552107775953345| 0.4435330811243698|0.4428211981522601| 0.4411382484653322| 0.2242624409451437|USC00099291| 8377438.0|     0|[28 58 E0 58 80 5...|1996.0|
|-967.9883270468604|-129.33239004154032|-105.40841156052838| 43.56010259625057|    107.0|BSBSSSSB| 32.3667| -83.9333|       TOBS|0.4656367450718231|0.45319433904308287|0.4435468381662791|0.44301573905405567|0.08436150685467123|USC00095555|2.132263E7|     2|[80 51 C8 5A 00 4...|1911.0|
+------------------+-------------------+-------------------+------------------+---------+--------+--------+---------+-----------+------------------+-------------------+------------------+-------------------+-------------------+-----------+----------+------+--------------------+------+
only showing top 2 rows

In [5]:
print df.columns

['coeff_1', 'coeff_2', 'coeff_3', 'coeff_4', 'elevation', 'label', 'latitude', 'longitude', 'measurement', 'res_1', 'res_2', 'res_3', 'res_4', 'res_mean', 'station', 'total_var', 'undefs', 'vector', 'year']

In [6]:
#extract longitude and latitude for each station
feature='coeff_1'
sqlContext.registerDataFrameAsTable(df,'weather')
#Features=', '.join(['coeff_1', 'coeff_2', 'coeff_3', 'elevation', 'latitude', 'longitude',\
#          'res_1', 'res_2', 'res_3', 'res_mean', 'year'])
Features='station, year, coeff_1, coeff_2, coeff_3'
Query="SELECT %s FROM weather"%Features
print(Query)
pdf = sqlContext.sql(Query).toPandas()
pdf.head()

SELECT station, year, coeff_1, coeff_2, coeff_3 FROM weather

       station    year      coeff_1     coeff_2     coeff_3
0  USC00099291  1996.0  1011.691584  148.119581   36.571114
1  USC00095555  1911.0  -967.988327 -129.332390 -105.408412
2  USC00016129  1990.0   969.842769 -269.296331 -151.122649
3  USC00016129  1964.0  1108.658871   43.714320   41.018041
4  USC00016501  1976.0  1194.317177 -183.549183  175.758216

In [7]:
year_station_table1=pdf.pivot(index='year', columns='station', values='coeff_1')
year_station_table1.head(10)

station,USC00010422,USC00010425,USC00010430,USC00011725,USC00012727,USC00012730,USC00014502,USC00016129,USC00016397,USC00016398,...,USC00097046,USC00097087,USC00097240,USC00098535,USC00098657,USC00098661,USC00099027,USC00099124,USC00099291,USC00099506
year,,,,,,,,,,,,,,,,,,,,,
1901.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,186.823211,NaN,NaN,NaN,NaN,NaN,NaN
1902.0,NaN,NaN,NaN,NaN,905.925497,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-29.497725,114.527841,NaN,NaN,NaN,NaN,NaN,1483.998423
1903.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,95.209389,149.807819,NaN,NaN,NaN,NaN,NaN,1328.300412
1904.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,29.931866,-5.344162,NaN,NaN,NaN,NaN,NaN,980.054271
1905.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-113.431638,208.348361,NaN,NaN,NaN,NaN,NaN,421.776263
1906.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-145.426456,-189.042088,NaN,NaN,NaN,NaN,1130.651045,124.568587
1907.0,-107.365823,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-155.100574,-414.932214,NaN,NaN,NaN,NaN,889.240632,-88.703800
1908.0,-146.391051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-249.278436,NaN,NaN,NaN,NaN,NaN,-521.634683
1909.0,-73.296605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,531.720644,-333.074863
1910.0,-133.152156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-146.817529,NaN,NaN,NaN,NaN,892.325702,NaN

In [8]:
year_station_table2=pdf.pivot(index='year', columns='station', values='coeff_2')
year_station_table2.head(10)

station,USC00010422,USC00010425,USC00010430,USC00011725,USC00012727,USC00012730,USC00014502,USC00016129,USC00016397,USC00016398,...,USC00097046,USC00097087,USC00097240,USC00098535,USC00098657,USC00098661,USC00099027,USC00099124,USC00099291,USC00099506
year,,,,,,,,,,,,,,,,,,,,,
1901.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-137.413533,NaN,NaN,NaN,NaN,NaN,NaN
1902.0,NaN,NaN,NaN,NaN,-116.579193,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-58.584469,111.117919,NaN,NaN,NaN,NaN,NaN,760.402333
1903.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-233.495310,-228.275052,NaN,NaN,NaN,NaN,NaN,-472.865170
1904.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,113.877719,-50.838627,NaN,NaN,NaN,NaN,NaN,180.695447
1905.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,150.516439,-56.213260,NaN,NaN,NaN,NaN,NaN,378.613814
1906.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-7.751174,-3.385148,NaN,NaN,NaN,NaN,-145.521666,142.933038
1907.0,-380.263924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-382.460028,-317.691202,NaN,NaN,NaN,NaN,-213.842423,-32.152603
1908.0,70.298133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-181.334218,NaN,NaN,NaN,NaN,NaN,171.060219
1909.0,-225.345318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-141.253753,-171.156928
1910.0,-121.207135,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-121.706357,NaN,NaN,NaN,NaN,84.039213,NaN

In [9]:
year_station_table3=pdf.pivot(index='year', columns='station', values='coeff_3')
year_station_table3.head(10)

station,USC00010422,USC00010425,USC00010430,USC00011725,USC00012727,USC00012730,USC00014502,USC00016129,USC00016397,USC00016398,...,USC00097046,USC00097087,USC00097240,USC00098535,USC00098657,USC00098661,USC00099027,USC00099124,USC00099291,USC00099506
year,,,,,,,,,,,,,,,,,,,,,
1901.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-71.084709,NaN,NaN,NaN,NaN,NaN,NaN
1902.0,NaN,NaN,NaN,NaN,96.014133,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-4.562650,48.259438,NaN,NaN,NaN,NaN,NaN,-215.989893
1903.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,59.489285,46.523810,NaN,NaN,NaN,NaN,NaN,139.171677
1904.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-88.545721,-38.730371,NaN,NaN,NaN,NaN,NaN,-64.279669
1905.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,132.205986,3.993554,NaN,NaN,NaN,NaN,NaN,77.325884
1906.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,62.152192,36.778204,NaN,NaN,NaN,NaN,-24.257195,-57.087275
1907.0,120.956351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,146.097011,135.013839,NaN,NaN,NaN,NaN,5.812521,-80.118711
1908.0,179.946556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,329.696027,NaN,NaN,NaN,NaN,NaN,202.911052
1909.0,-31.753823,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-44.547222,-14.931452
1910.0,102.793431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,104.853145,NaN,NaN,NaN,NaN,-30.783219,NaN

### Estimating the effect of the year vs the effect of the station

To estimate the effect of time vs. location on the first eigenvector coefficient we
compute:

* The average row: `mean-by-station`
* The average column: `mean-by-year`

We then compute the RMS before and after subtracting either  the row or the column vector.

In [10]:
# ORIGINALITY: Changed RMS to MS. Also, implemented PrintFractionExplained function to explain the fraction by which variance is reduced 
# when we subtract from each station/year entry the average-per-year or the average-per-station respectively. 
# We print these for coeff1, coeff2 and coeff3. These results are also included in the report.

def MS(Mat):
    return np.nanmean(Mat**2)

def PrintFractionExplained(year_station_table):
    mean_by_year=np.nanmean(year_station_table,axis=1)
    mean_by_station=np.nanmean(year_station_table,axis=0)
    tbl_minus_year = (year_station_table.transpose()-mean_by_year).transpose()
    tbl_minus_station = year_station_table-mean_by_station
    print 'total MS                   = ',MS(year_station_table)
    print 'MS removing mean-by-station= ',MS(tbl_minus_station)
    print 'Fraction Explained = ',(MS(year_station_table)-MS(tbl_minus_station))/MS(year_station_table)*100
    print 'MS removing mean-by-year   = ',MS(tbl_minus_year)
    print 'Fraction Explained = ',(MS(year_station_table)-MS(tbl_minus_year))/MS(year_station_table)*100
    
PrintFractionExplained(year_station_table1)
PrintFractionExplained(year_station_table2)
PrintFractionExplained(year_station_table3)

total MS                   =  474281.847681
MS removing mean-by-station=  235389.207946
Fraction Explained =  50.3693406997
MS removing mean-by-year   =  348154.794874
Fraction Explained =  26.5932701037
total MS                   =  38193.7391873
MS removing mean-by-station=  34362.8992774
Fraction Explained =  10.0300206039
MS removing mean-by-year   =  13070.610299
Fraction Explained =  65.7781338587
total MS                   =  29287.9121458
MS removing mean-by-station=  27747.2174274
Fraction Explained =  5.26051399888
MS removing mean-by-year   =  4513.61237665
Fraction Explained =  84.588821647

In [11]:
year_station_table=pdf.pivot(index='year', columns='station', values='coeff_2')
year_station_table.head(10)

station,USC00010422,USC00010425,USC00010430,USC00011725,USC00012727,USC00012730,USC00014502,USC00016129,USC00016397,USC00016398,...,USC00097046,USC00097087,USC00097240,USC00098535,USC00098657,USC00098661,USC00099027,USC00099124,USC00099291,USC00099506
year,,,,,,,,,,,,,,,,,,,,,
1901.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-137.413533,NaN,NaN,NaN,NaN,NaN,NaN
1902.0,NaN,NaN,NaN,NaN,-116.579193,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-58.584469,111.117919,NaN,NaN,NaN,NaN,NaN,760.402333
1903.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-233.495310,-228.275052,NaN,NaN,NaN,NaN,NaN,-472.865170
1904.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,113.877719,-50.838627,NaN,NaN,NaN,NaN,NaN,180.695447
1905.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,150.516439,-56.213260,NaN,NaN,NaN,NaN,NaN,378.613814
1906.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-7.751174,-3.385148,NaN,NaN,NaN,NaN,-145.521666,142.933038
1907.0,-380.263924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-382.460028,-317.691202,NaN,NaN,NaN,NaN,-213.842423,-32.152603
1908.0,70.298133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-181.334218,NaN,NaN,NaN,NaN,NaN,171.060219
1909.0,-225.345318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-141.253753,-171.156928
1910.0,-121.207135,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-121.706357,NaN,NaN,NaN,NaN,84.039213,NaN

In [12]:
mean_by_year=np.nanmean(year_station_table,axis=1)
mean_by_station=np.nanmean(year_station_table,axis=0)
tbl_minus_year = (year_station_table.transpose()-mean_by_year).transpose()
tbl_minus_station = year_station_table-mean_by_station

T=year_station_table
print 'initial MS=',MS(T)
for i in range(5):
    mean_by_year=np.nanmean(T,axis=1)
    T=(T.transpose()-mean_by_year).transpose()
    print i,'after removing mean by year    =',MS(T)
    mean_by_station=np.nanmean(T,axis=0)
    T=T-mean_by_station
    print i,'after removing mean by stations=',MS(T)

initial MS= 38193.7391873
0 after removing mean by year    = 13070.610299
0 after removing mean by stations= 11006.1388068
1 after removing mean by year    = 10935.8031872
1 after removing mean by stations= 10926.3049002
2 after removing mean by year    = 10922.963868
2 after removing mean by stations= 10921.2913877
3 after removing mean by year    = 10920.3747217
3 after removing mean by stations= 10919.8583574
4 after removing mean by year    = 10919.5643497
4 after removing mean by stations= 10919.3961231